/* Exercicio 01  - Gatilhos */

CREATE DATABASE bd_trigger01
use bd_trigger01

DROP TABLE TB_ALUNO 
DROP TABLE TB_LOG_PENDENCIAS

CREATE TABLE TB_ALUNO (
    MATRICULA INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    RG VARCHAR(60) NULL,
    ENDERECO VARCHAR(10) NULL,
    TELEFONE VARCHAR (10) NULL,
)


CREATE TABLE TB_LOG_PENDENCIAS (
  MATRICULA INT,
  NOME VARCHAR(50),
  PENDENCIA VARCHAR(200)
)
 
-- Questão 01 (Cursores) --
CREATE OR ALTER TRIGGER TG_ALUNO_INSERT
ON TB_ALUNO
AFTER INSERT 
AS 
BEGIN 
	DECLARE @MATRICULA INT,
	        @NOME VARCHAR(50),
	        @RG VARCHAR(60),
	        @ENDERECO VARCHAR(10),
	        @TELEFONE VARCHAR(10)

	DECLARE C_ALUNO CURSOR FOR SELECT MATRICULA, NOME, RG, ENDERECO, TELEFONE
	                           FROM INSERTED 
	OPEN C_ALUNO
	FETCH C_ALUNO INTO @MATRICULA, @NOME, @RG, @ENDERECO, @TELEFONE
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		IF (@RG IS NULL)
		   INSERT INTO TB_LOG_PENDENCIAS VALUES (@MATRICULA, @NOME, 'FALTA RG')
		IF (@ENDERECO IS NULL)
		   INSERT INTO TB_LOG_PENDENCIAS VALUES (@MATRICULA, @NOME , 'FALTA ENDERECO')
		IF (@TELEFONE IS NULL)
		   INSERT INTO TB_LOG_PENDENCIAS VALUES (@MATRICULA, @NOME , 'FALTA TELEFONE')
		FETCH C_ALUNO INTO @MATRICULA, @NOME, @RG, @ENDERECO, @TELEFONE
	END
	CLOSE C_ALUNO
	DEALLOCATE C_ALUNO
END


INSERT INTO TB_ALUNO VALUES (1, 'ANDRE', '89999', NULL, NULL)

INSERT INTO TB_ALUNO VALUES (2, 'JOAO', '9999', NULL, NULL)

INSERT INTO TB_ALUNO VALUES (3, 'PATRICIA', '89999', NULL, NULL),
                            (4, 'JOANA', '9999', NULL, NULL)








-- Testes
DELETE FROM TB_ALUNO
DELETE FROM TB_LOG_PENDENCIAS

INSERT INTO TB_ALUNO VALUES(1, 'JOAO',NULL,NULL,NULL)
INSERT INTO TB_ALUNO VALUES(2, 'GUSTAVO',NULL,'RUA H',NULL)

SELECT * FROM TB_ALUNO
SELECT * FROM TB_LOG_PENDENCIAS

-- Questao 1  (Sem Cursores) --

CREATE OR ALTER TRIGGER TG_ALUNO_INSERT
ON TB_ALUNO
AFTER INSERT
AS 

INSERT INTO TB_LOG_PENDENCIAS

SELECT MATRICULA, NOME, 'FALTA RG'
FROM INSERTED 
WHERE RG IS NULL

UNION ALL

SELECT MATRICULA, NOME, 'FALTA ENDERECO'
FROM INSERTED 
WHERE ENDERECO IS NULL

UNION ALL

SELECT MATRICULA, NOME, 'FALTA TELEFONE'
FROM INSERTED
WHERE TELEFONE IS NULL

-- Testes

INSERT INTO TB_ALUNO VALUES(1, 'JOAO',NULL,NULL,NULL)
INSERT INTO TB_ALUNO VALUES(2, 'GUSTAVO',NULL,'RUA H',NULL)

SELECT * FROM TB_LOG_PENDENCIAS


---------------------------------------------------------------------------------------------------------

-- Questão 02 (Cursores) --

CREATE TRIGGER TG_ALUNO_UPDATE
ON TB_ALUNO
AFTER UPDATE
AS 
BEGIN 
	DECLARE @MATRICULA INT,
	        @NOME VARCHAR(50),
	        @RG VARCHAR(60),
	        @ENDERECO VARCHAR(10),
	        @TELEFONE VARCHAR(10)

	DECLARE C_ALUNO CURSOR FOR SELECT MATRICULA, NOME, RG, ENDERECO, TELEFONE
	                           FROM INSERTED 
	OPEN C_ALUNO
	FETCH C_ALUNO INTO @MATRICULA, @NOME, @RG, @ENDERECO, @TELEFONE
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		DELETE FROM TB_LOG_PENDENCIAS WHERE MATRICULA = @MATRICULA
		IF (@RG IS NULL)
		   INSERT INTO TB_LOG_PENDENCIAS VALUES (@MATRICULA, @NOME, 'FALTA RG')
		IF (@ENDERECO IS NULL)
		   INSERT INTO TB_LOG_PENDENCIAS VALUES (@MATRICULA, @NOME , 'FALTA ENDERECO')
		IF (@TELEFONE IS NULL)
		   INSERT INTO TB_LOG_PENDENCIAS VALUES (@MATRICULA, @NOME , 'FALTA TELEFONE')
		FETCH C_ALUNO INTO @MATRICULA, @NOME, @RG, @ENDERECO, @TELEFONE
	END
	CLOSE C_ALUNO
	DEALLOCATE C_ALUNO
END


-- Testes

INSERT INTO TB_ALUNO VALUES(1, 'JOAO',NULL,NULL,NULL)
INSERT INTO TB_ALUNO VALUES(2, 'GUSTAVO',NULL,'RUA H',NULL)
INSERT INTO TB_ALUNO VALUES(3, 'PATRICIA','123','RUA H',NULL)

UPDATE TB_ALUNO
SET RG = '123456'
WHERE MATRICULA = 1

UPDATE TB_ALUNO
SET TELEFONE = '9884848'


SELECT * FROM TB_LOG_PENDENCIAS


-- Questão 2 (Sem Cursores)

ALTER TRIGGER TG_ALUNO_UPDATE
ON TB_ALUNO
AFTER UPDATE
AS 
DELETE FROM TB_LOG_PENDENCIAS
WHERE MATRICULA IN (SELECT MATRICULA FROM INSERTED)

INSERT INTO TB_LOG_PENDENCIAS

SELECT MATRICULA, NOME, 'FALTA RG'
FROM INSERTED 
WHERE RG IS NULL

UNION ALL

SELECT MATRICULA, NOME,'FALTA ENDERECO'
FROM INSERTED 
WHERE ENDERECO IS NULL

UNION ALL

SELECT MATRICULA, NOME, 'FALTA TELEFONE'
FROM INSERTED
WHERE TELEFONE IS NULL

-- Testes

UPDATE TB_ALUNO
SET RG = '123456'
WHERE MATRICULA = 1

UPDATE TB_ALUNO
SET TELEFONE = '123456'


INSERT INTO TB_ALUNO VALUES(1, 'JOAO',NULL,NULL,NULL)
INSERT INTO TB_ALUNO VALUES(2, 'GUSTAVO',NULL,'RUA H',NULL)
INSERT INTO TB_ALUNO VALUES(3, 'PATRICIA','123','RUA H',NULL)


SELECT * FROM TB_LOG_PENDENCIAS

---------------------------------------------------------------------------------------------------------
-- Questao 3 (Cursores)

CREATE TRIGGER TG_ALUNO_DELETE
ON TB_ALUNO
AFTER DELETE
AS 
BEGIN 
	DECLARE @MATRICULA INT
	       
	DECLARE C_ALUNO CURSOR FOR SELECT MATRICULA FROM DELETED
	OPEN C_ALUNO
	FETCH C_ALUNO INTO @MATRICULA
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		DELETE FROM TB_LOG_PENDENCIAS WHERE MATRICULA = @MATRICULA
		FETCH C_ALUNO INTO @MATRICULA
	END
	CLOSE C_ALUNO
	DEALLOCATE C_ALUNO
END


-- Questao 3 (Sem Cursores)

CREATE TRIGGER TG_ALUNO_DELETE
ON TB_ALUNO
AFTER DELETE
AS 
DELETE FROM TB_LOG_PENDENCIAS
WHERE MATRICULA IN (SELECT MATRICULA FROM DELETED)

-- Testes

DELETE FROM TB_ALUNO
WHERE MATRICULA = 1

SELECT * FROM TB_LOG_PENDENCIAS