/* Exercício Adicional Cursor 01 - Procedimentos Armazenados */

CREATE DATABASE lab_cursor
use lab_cursor


CREATE TABLE TB_ALUNO (
   MATRICULA INT NOT NULL PRIMARY KEY,
   NOME VARCHAR(100) NOT NULL,
   DT_NASCIMENTO DATETIME NOT NULL
)   

INSERT INTO TB_ALUNO VALUES 
(1, 'JOAO', '19760812'),
(2, 'RICARDO', '19700123'),
(3, 'ROBERTO', '19890726')


SELECT * FROM TB_ALUNO



CREATE OR ALTER PROCEDURE SP_RELATORIO_ALUNOS
AS
BEGIN
DECLARE @MATRICULA INT, @NOME VARCHAR(50),
        @DT_NASCIMENTO DATETIME,
		@TOTAL INT

DECLARE  C_ALUNO CURSOR FOR 
SELECT MATRICULA, NOME, DT_NASCIMENTO
FROM TB_ALUNO

PRINT '            ALUNOS MATRICULADOS' 
PRINT ''
PRINT 'MATRICULA		NOME		DATA NASCIMENTO'
PRINT (REPLICATE('-',45))
SET @TOTAL = 0
OPEN C_ALUNO
FETCH C_ALUNO INTO @MATRICULA, @NOME, @DT_NASCIMENTO
WHILE (@@FETCH_STATUS = 0)
  BEGIN
   PRINT LTRIM(STR(@MATRICULA)) + REPLICATE(CHAR(9),4) + @NOME +
         REPLICATE(CHAR(9),2) +
         CONVERT(VARCHAR(10), @DT_NASCIMENTO,103)
   PRINT (REPLICATE('-',45))
   SET @TOTAL = @TOTAL + 1
   FETCH C_ALUNO INTO @MATRICULA, @NOME, @DT_NASCIMENTO
  END
  PRINT ('TOTAL DE ALUNOS: ' + TRIM(STR(@TOTAL)))
CLOSE C_ALUNO
DEALLOCATE C_ALUNO
END


EXEC SP_RELATORIO_ALUNOS




