
use bdII_visoes01

a. Criar uma Visão VW_ANIMAIS_RACA. A visão deve apresentar 
   todos os animais e as suas raças.  

CREATE VIEW VW_ANIMAIS_RACA
AS
SELECT A.NM_ANIMAL, R.NM_RACA
FROM TB_ANIMAL A INNER JOIN TB_RACA R
ON (A.CD_RACA = R.CD_RACA)


b.Criar uma Visão VW_ANIMAIS_PROPRIETARIOS que apresente os 
  seguintes atributos: NM_PROPRIETARIO, NM_ANIMAL, NM_RACA.
  Somente os proprietários que tiverem animais devem aparecer
  no resultado.


CREATE VIEW VW_ANIMAIS_PROPRIETARIOS
AS
SELECT P.NM_PROPRIETARIO, A.NM_ANIMAL, R.NM_RACA
FROM TB_PROPRIETARIO P INNER JOIN TB_ANIMAL A 
ON (P.CD_PROPRIETARIO = A.CD_PROPRIETARIO)
INNER JOIN TB_RACA R
ON (A.CD_RACA = R.CD_RACA)



SELECT P.NM_PROPRIETARIO, A.NM_ANIMAL, R.NM_RACA
FROM TB_PROPRIETARIO P LEFT JOIN TB_ANIMAL A 
ON (P.CD_PROPRIETARIO = A.CD_PROPRIETARIO)
LEFT JOIN TB_RACA R
ON (A.CD_RACA = R.CD_RACA)    


c.Criar uma Visão VW_CONSULTAS que apresente o total de consultas
  por animal. A visão deve apresentar os seguintes 
  atributos: CD_ANIMAL, NM_ANIMAL, TOTAL_CONSULTAS.


CREATE VIEW VW_CONSULTAS 
AS
SELECT A.CD_ANIMAL, A.NM_ANIMAL, COUNT(C.CD_CONSULTA) AS TOTAL_CONSULTAS
FROM TB_CONSULTA C INNER JOIN TB_ANIMAL A
ON (C.CD_ANIMAL = A.CD_ANIMAL)
GROUP BY A.CD_ANIMAL, A.NM_ANIMAL


d.Criar uma Visão VW_ULTIMA_CONSULTA para apresentar a data 
  da última consulta de cada animal. O resultado deve apresentar 
  os seguintes atributos: CD_ANIMAL, NM_ANIMAL, 'DATA DA ULTIMA CONSULTA'. 


CREATE VIEW VW_ULTIMA_CONSULTA 
AS
SELECT A.CD_ANIMAL, A.NM_ANIMAL, MAX(C.DT_CONSULTA) AS 'DATA DA ULTIMA CONSULTA'
FROM TB_CONSULTA C INNER JOIN TB_ANIMAL A
ON (C.CD_ANIMAL = A.CD_ANIMAL)
GROUP BY A.CD_ANIMAL, A.NM_ANIMAL