/* Exercicio 03 - Visões Particionadas */

USE lab01
DROP TABLE TB_FUNCIONARIO_SE
DROP TABLE TB_FUNCIONARIO_PB
DROP TABLE TB_FUNCIONARIO_AL

CREATE TABLE TB_FUNCIONARIO_SE (
   MATRICULA INT NOT NULL,
   NM_FUNCIONARIO VARCHAR(40) NOT NULL,
   ESTADO CHAR(2) NOT NULL CHECK (ESTADO IN ('SE')),
   SALARIO NUMERIC(10,2),
   PRIMARY KEY(MATRICULA, ESTADO)
)

CREATE TABLE TB_FUNCIONARIO_PB (
   MATRICULA INT NOT NULL,
   NM_FUNCIONARIO VARCHAR(40) NOT NULL,
   ESTADO CHAR(2) NOT NULL CHECK (ESTADO IN ('PB')),
   SALARIO NUMERIC(10,2),
   PRIMARY KEY(MATRICULA, ESTADO)
)

CREATE TABLE TB_FUNCIONARIO_AL (
   MATRICULA INT NOT NULL,
   NM_FUNCIONARIO VARCHAR(40) NOT NULL,
   ESTADO CHAR(2) NOT NULL CHECK (ESTADO IN ('AL')),
   SALARIO NUMERIC(10,2),
   PRIMARY KEY(MATRICULA, ESTADO)
)


DROP VIEW VW_FUNCIONARIO
CREATE VIEW VW_FUNCIONARIO
AS
SELECT * FROM TB_FUNCIONARIO_SE
UNION ALL
SELECT * FROM TB_FUNCIONARIO_PB
UNION ALL
SELECT * FROM TB_FUNCIONARIO_AL

INSERT INTO VW_FUNCIONARIO
VALUES (1,'JOAO', 'PB',2000.00)

SELECT * FROM TB_FUNCIONARIO_PB

UPDATE VW_FUNCIONARIO
SET ESTADO = 'SE'
WHERE MATRICULA = 1

SELECT * FROM TB_FUNCIONARIO_SE
