CREATE OR ALTER TRIGGER TG_DDL_TABLE_PREFIX
ON DATABASE
for CREATE_TABLE
AS
BEGIN
DECLARE @EVENT XML
SET @EVENT = EVENTDATA()
DECLARE @VARI nvarchar(2000)
set @VARI = @EVENT.value('(/EVENT_INSTANCE/TSQLCommand/CommandText)[1]','nvarchar(2000)')
SET @VARI = SUBSTRING(UPPER(@VARI),14,3)
PRINT @VARI
IF @VARI <> 'TB_'
BEGIN
	RAISERROR('ERROR',1,1)
	ROLLBACK
	RETURN
END
PRINT @VARI
END

CREATE TABLE  TB_OI(X INT PRIMARY KEY)

DROP TABLE TB_OI