CREATE DATABASE BD2_LAB_07

CREATE TABLE TB_FUNCIONARIO (
  MATRICULA INT NOT NULL PRIMARY KEY,
  NOME  VARCHAR(100) NOT NULL,
  CARGO VARCHAR(100) NOT NULL,
  SALARIO NUMERIC (10,2)
) 

/* Tabela para log de alterações na tabela de Funcionario. As alterações podem
   ser de três tipos: (I - Inclusao, A - Alteracao, R - Remocao).  */


CREATE TABLE TB_LOG_FUNCIONARIO
(
    CD_LOG 		INT IDENTITY (1,1) NOT NULL,
    DT_LOG 		DATETIME NOT NULL,     -- Data em que o log foi registrado
    TIPO_OPERACAO 	CHAR(1) CHECK (TIPO_OPERACAO IN ('I','A','R')),	
    MATRICULA 		INT NOT NULL,
    NOME  		VARCHAR(100) NOT NULL,
    MODIFICACAO		VARCHAR(500) NOT NULL
)

GO
CREATE OR ALTER TRIGGER TG_INSERT_FUNCIONARIO
ON TB_FUNCIONARIO
AFTER INSERT
AS
BEGIN
	DECLARE @MATRICULA INT, @NOME VARCHAR(100)
	SELECT @MATRICULA = I.MATRICULA, @NOME = I.NOME FROM INSERTED I

	INSERT INTO TB_LOG_FUNCIONARIO(DT_LOG,TIPO_OPERACAO,MATRICULA,NOME,MODIFICACAO)
	VALUES(
	GETDATE(),
	'I',
	@MATRICULA,
	@NOME,
	'Inclusão de novo funcionário'
	)
END
GO

GO
CREATE OR ALTER TRIGGER TG_DELETE_FUNCIONARIO
ON TB_FUNCIONARIO
AFTER DELETE
AS
BEGIN
	DECLARE @MATRICULA INT, @NOME VARCHAR(100)
	SELECT @MATRICULA = D.MATRICULA, @NOME = D.NOME FROM DELETED D

	INSERT INTO TB_LOG_FUNCIONARIO(DT_LOG,TIPO_OPERACAO,MATRICULA,NOME,MODIFICACAO)
	VALUES(
	GETDATE(),
	'R',
	@MATRICULA,
	@NOME,
	'Remoção de funcionário'
	)
END
GO

GO
CREATE OR ALTER TRIGGER TG_UPDATE_FUNCIONARIO
ON TB_FUNCIONARIO
AFTER UPDATE
AS
BEGIN
	DECLARE @MATRICULA INT, @NOME VARCHAR(100), @SALARIO_ANTIGO NUMERIC(10,2), @SALARIO_NOVO NUMERIC(10,2), @CARGO_ANTIGO VARCHAR(100), @CARGO_NOVO VARCHAR(100)
	SELECT @MATRICULA = D.MATRICULA, @NOME = D.NOME, @SALARIO_ANTIGO = D.SALARIO, @CARGO_ANTIGO = D.CARGO FROM DELETED D
	SELECT @SALARIO_NOVO = SALARIO, @CARGO_NOVO = CARGO FROM INSERTED 

	IF @SALARIO_NOVO > @SALARIO_ANTIGO
	BEGIN
		INSERT INTO TB_LOG_FUNCIONARIO(DT_LOG,TIPO_OPERACAO,MATRICULA,NOME,MODIFICACAO)
		VALUES(
		GETDATE(),
		'A',
		@MATRICULA,
		@NOME,
		'Aumento de Salário'
		)
	END

	IF @SALARIO_NOVO < @SALARIO_ANTIGO
	BEGIN
		INSERT INTO TB_LOG_FUNCIONARIO(DT_LOG,TIPO_OPERACAO,MATRICULA,NOME,MODIFICACAO)
		VALUES(
		GETDATE(),
		'A',
		@MATRICULA,
		@NOME,
		'Redução de Salário'
		)
	END

	IF @CARGO_ANTIGO <> @CARGO_NOVO
	BEGIN
		INSERT INTO TB_LOG_FUNCIONARIO(DT_LOG,TIPO_OPERACAO,MATRICULA,NOME,MODIFICACAO)
		VALUES(
		GETDATE(),
		'A',
		@MATRICULA,
		@NOME,
		'Alteração de Cargo'
		)
	END
	
END
GO


SELECT * FROM TB_FUNCIONARIO
SELECT * FROM TB_LOG_FUNCIONARIO

INSERT INTO TB_FUNCIONARIO
VALUES(1,'KENDY','TI',20000)

DELETE FROM TB_FUNCIONARIO
WHERE MATRICULA = 1

UPDATE TB_FUNCIONARIO
SET  SALARIO = 1000
WHERE MATRICULA = 1

