1. Criar uma tabela TB_FUNCIONARIO com os atributos: 
   MATRICULA, NOME, TELEFONE, ENDERECO, SALARIO, PENDENCIA. 
   Somente os atributos MATRICULA e NOME são obrigatórios.

CREATE TABLE TB_FUNCIONARIO (
  MATRICULA INT NOT NULL,
  NOME VARCHAR(40) NOT NULL,
  TELEFONE VARCHAR(20) NULL,
  ENDERECO VARCHAR(30) NULL,
  SALARIO NUMERIC(10,2) NULL,
  PENDENCIA VARCHAR(200) NULL
)


2. Criar um procedimento armazenado que, 
   utilizando um cursor, percorra a tabela TB_FUNCIONARIO e 
   atualize o campo de PENDENCIA.

O campo de PENDENCIA deverá conter:

a. O texto SEM PENDÊNCIA quando todos os atributos de um funcionário
   apresentarem valores.
b. Um texto 'EXISTE PENDÊNCIA' quando existirem atributos 
   sem valores.

CREATE PROCEDURE SP_ATUALIZA_PENDENCIA
AS
DECLARE @MATRICULA INT,
        @TELEFONE VARCHAR(20),
	@ENDERECO VARCHAR(30),
	@SALARIO NUMERIC(10,2),
	@PENDENCIA VARCHAR(200)

DECLARE C_FUNCIONARIO CURSOR FOR
SELECT MATRICULA, TELEFONE,ENDERECO,SALARIO
FROM TB_FUNCIONARIO

OPEN C_FUNCIONARIO
FETCH C_FUNCIONARIO INTO @MATRICULA, @TELEFONE, @ENDERECO, @SALARIO
WHILE (@@FETCH_STATUS =0)
BEGIN
   SET @PENDENCIA = 'SEM PENDENCIA'
   IF @TELEFONE IS NULL OR @ENDERECO IS NULL 
      OR @SALARIO IS NULL
	SET @PENDENCIA = 'EXISTE PENDENCIA'
   UPDATE TB_FUNCIONARIO
   SET PENDENCIA = @PENDENCIA
   WHERE MATRICULA = @MATRICULA
   FETCH C_FUNCIONARIO INTO @MATRICULA, @TELEFONE, @ENDERECO, @SALARIO
END
CLOSE C_FUNCIONARIO 
DEALLOCATE C_FUNCIONARIO 

-- TESTE
SELECT * FROM TB_FUNCIONARIO
INSERT INTO TB_FUNCIONARIO VALUES(1,'JOAO',NULL,NULL,NULL,NULL)
INSERT INTO TB_FUNCIONARIO VALUES(2,'PEDRO','99999',NULL,45.0,NULL)
INSERT INTO TB_FUNCIONARIO VALUES(3,'CARLOS',NULL,NULL,45.00,NULL)
INSERT INTO TB_FUNCIONARIO VALUES(4,'JOSE',NULL,'RUA F',NULL,NULL)
INSERT INTO TB_FUNCIONARIO VALUES(5,'PATRICIA',NULL,'RUA J',100.0,NULL)
INSERT INTO TB_FUNCIONARIO VALUES(6,'ROBERTO','2222','RUA H',NULL,NULL)
INSERT INTO TB_FUNCIONARIO VALUES(7,'ANDRE','2222','RUA H',2000.0,NULL)

EXEC SP_ATUALIZA_PENDENCIA

SELECT * FROM TB_FUNCIONARIO


-- Solução 02

CREATE PROCEDURE SP_ATUALIZA_PENDENCIA
AS
DECLARE  @TELEFONE VARCHAR(20),
	@ENDERECO VARCHAR(30),
	@SALARIO NUMERIC(10,2),
	@PENDENCIA VARCHAR(200)

DECLARE C_FUNCIONARIO CURSOR FOR
SELECT TELEFONE,ENDERECO,SALARIO
FROM TB_FUNCIONARIO

OPEN C_FUNCIONARIO
FETCH C_FUNCIONARIO INTO @TELEFONE, @ENDERECO, @SALARIO
WHILE (@@FETCH_STATUS =0)
BEGIN
   SET @PENDENCIA = 'SEM PENDENCIA'
   IF @TELEFONE IS NULL OR @ENDERECO IS NULL 
      OR @SALARIO IS NULL
	SET @PENDENCIA = 'EXISTE PENDENCIA'
   UPDATE TB_FUNCIONARIO
   SET PENDENCIA = @PENDENCIA
   WHERE CURRENT OF C_FUNCIONARIO
   FETCH C_FUNCIONARIO INTO  @TELEFONE, @ENDERECO, @SALARIO
END
CLOSE C_FUNCIONARIO 
DEALLOCATE C_FUNCIONARIO 

			     


	

